extends:
  - eslint:recommended
  - standard

env:
  es2021: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  comma-dangle: [error, always-multiline]
  eqeqeq: off # or [error, smart]
  no-console:
    - error
    - allow: [warn, error]
  no-new-func: off
  no-useless-call: off
  space-before-function-paren:
    - error
    - named: never
